# version: '3.8'
# services:
#   db:
#     image: postgres:14.7-alpine
#     restart: always
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#     ports:
#       - '5432:5432'
#     volumes: 
#       - db:/var/lib/postgresql/data
# volumes:
#   db:
#     driver: local

version: '3.8'
services:
  db:
    build: ./db
    restart: always
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    container_name: server
    volumes:
       - ./server:/usr/src/app/server
       - /usr/src/app/server/node_modules
  react-ui:
    build:
      context: ./client
    ports:
      - "3000:3000"
    container_name: client
    stdin_open: true
    volumes:
       - ./client:/usr/src/app/client
       - /usr/src/app/client/node_modules

volumes:
  db:
    driver: local