name: Docker Compose Actions Workflow
on: push

jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build the stack
        run: docker-compose up -d
      - name: Install dependencies
        working-directory: ./playwright-tests
        run: npm install
      - name: Install Playwright Browsers
        working-directory: ./playwright-tests
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: ./playwright-tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-tests/playwright-report/
          retention-days: 30
     